### ISSUE TITLE
Image identity

### ISSUE THREAD

**Issue by SamuelTallet** [EmbarkStudios/kajiya#56]
Hello! 🙂

In an iterative process, we need to anticipate and economize the redundant ops.

For instance, when a mesh changes but not the images associated to this mesh: I would like to bake these `*.image` files **only once** (currently, the `bake` app processes and overwrites the `*.image` files each time).

Is it possible to bake an image before a mesh in a **separate** call of the `bake` app, so the `*.image` files are ready as soon as possible?

How is computed the image identity we find in `*.image` filename? For instance, `4687d169d3f192b8.image`. Is this identity predictable?

**Comment by h3r2tic** [comment]
Hey!

The `bake` app is a very very poor approximation of an asset pipeline. It doesn't really support partial builds. It's currently layered on top of a lazy evaluation framework, but one for _runtime_ lazy re-computation rather than asset builds. It was just a quick hack to convert meshes and textures into something that can be loaded via memory-maped files.

I believe the texture identity store is inconsistent too, with it being a hash of the URI for free-standing images, and a content ID for ones embedded in GLB files.
