### ISSUE TITLE
Question: Thoughts on pure raytracing?

### ISSUE THREAD

**Issue by rishflab** [EmbarkStudios/kajiya#59]
First of all, great work. GI done properly looks amazing.

In your opinion do you think a pure raytracing version of the demo (with enough samples to achieve similar visual quality) would run in realtime?

During the development phase, did you give pure raytracing a shot?

I am trying to figure out whether pure interactive raytracing is possible for relatively simple games/environments with current hardware.

**Comment by mickvangelderen** [comment]
If you're going to shoot 1 ray per pixel from the camera into the scene the utilizing rasterization in the implementation makes a lot of sense since there is a lot of hardware out there which can do that very well.

Of course if you're looking for some effects that are difficult to realize through rasterization then it may make sense to do a ray tracing only implementation but, as far as I am aware, that comes at a performance cost on most hardware.

Why are you interested in pure raytracing?
